mock and skip mechanism for act
kiegroup/mock-github pull request #46
Opened 2022-11-04 09:46 UTC by Ginxo

2022-11-04 09:56 UTC, Ginxo commented on src/act/act.ts
> +      treatSteps(jobs, path.join(this.cwd, ".github", "workflows"), opts.steps)
@shubhbapna is this ".github/workflows" path always like that?

2022-11-04 09:58 UTC, Ginxo commented on test/.github/workflows/publish.test.ts
> +    const result = await act.runJob(jobId, {steps: {mock: [{name: "npm publish --access public", run: "echo 'publish step mocked'"}]}});
this is the new mock feature

2022-11-04 17:58 UTC, shubhbapna requested changes
Some file structure changes to keep things consistent
- Remove `test/action-compiler/compiled.js`
- `src/shared/domain/github-workflow.types.ts` seems to be only used act `act` so I think it would make more sense to shift this file to `src/act`
- `src/shared/util/fs-util.ts` again seems to be used only by `act`. Should we shift it to act-helper? If not we can at least reduce the directory nesting and just have it as `src/util/fs-util.ts`?

Class consistency:
- For `src/act/act-helper.ts` why not have these functions as private methods of the `Act` class? If not should keep it consistent and convert this act-helper file from using functions to a class to keep things consistent?

2022-11-04 17:58 UTC, shubhbapna commented on src/shared/util/fs-util.ts
> +        throw new Error(`Error parsing yaml from file ${filePath}`)
Same comment as `readFileSync`

2022-11-04 17:58 UTC, shubhbapna commented on test/.github/workflows/publish.test.ts
> +    const result = await act.runJob(jobId, {steps: {mock: [{name: "npm publish --access public", run: "echo 'publish step mocked'"}]}});
Love it!

2022-11-07 07:53 UTC, Ginxo commented on src/act/act.ts
> +      treatSteps(jobs, path.join(this.cwd, ".github", "workflows"), opts.steps)
I agree, I will try that

2022-11-23 00:36 UTC, shubhbapna commented
Moving `Act` to `act-js`. So won't be able merge this PR.

I will pick the non Act changes and open a separate PR

2022-11-30 14:30 UTC, shubhbapna commented
fixed by #50

2022-11-30 14:30 UTC, closed without merging