feat: Migrate to undici MockClient
kiegroup/mock-github pull request #79
Opened 2023-10-27 16:10 UTC by oliversalzburg

Breaking change!

- Internally uses `undici`'s `MockAgent`, instead of `nock` to mock requests.
- `nock` is still used for data-matching to retain backwards compatibility.
- Tests now use `fetch` instead of `axios`.

Requires node>=18 and @octokit/rest>=20

2023-10-30 02:13 UTC, shubhbapna commented
Thank you for your PR! I will take a look at the changes over this week

2023-11-13 09:17 UTC, oliversalzburg commented
@shubhbapna  Please let me know if the chance to have this merged is low. I can also transition my project to my fork.

2023-11-14 16:46 UTC, shubhbapna requested changes
So sorry for the delay! It slipped through the cracks for me.

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/abstract-endpoint-mocker.ts
> +  }
Could you explain why we need this? I think this is more of a jest issue where the jest globals differ from node globals: https://github.com/jestjs/jest/issues/2549. So we could leave the workaround for this user where, the user has to configure the globals correctly

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +import { EndpointMethod } from "../endpoint-mocker.types";
use `@mg` paths and not relative paths

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +            "content-type": this.getContentTypeForResponseData(response.data),
user can set this header in their response object. I want the user to have complete control over all response headers as well cause you never know what they are testing for. Maybe they just need to set the content-type header to form data but not really set the data in the reply.

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +  }
not needed

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +    const [pathname, search] = requestPath.split("?");
I don't think we will be passing query params in the path since we have a nicer way to pass queries. So if user tries to pass query params via path, I think it is fine if we use the default undici behavior which will throw an error

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +        query: this.query,
I wasn't able to find the docs on this, but does undici match queries based on regex as well?

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +      body: requestBody => this.bodyHandler(requestBody),
missing query matching

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +      this.agent.get(this.baseUrl).intercept({
Doesn't seem to be using headers for request matching? Is it not possible in undici?

2023-11-14 16:46 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +    return this.requestBody ? matchBody({}, this.requestBody, requestBody) : true;
undici does not do regex body matching? Is that why we need the matchBody from nock?

2023-11-14 16:52 UTC, oliversalzburg commented on src/moctokit/moctokit.ts
> +import diagnosticsChannel from "diagnostics_channel";
Yes. Will be removed.

2023-11-14 18:10 UTC, oliversalzburg reviewed
I addressed the comments and I'll work on some changes.

2023-11-14 18:10 UTC, oliversalzburg commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +        query: this.query,
Queries are matched as part of the path. See further comments on this below.

2023-11-14 18:10 UTC, oliversalzburg commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +      this.agent.get(this.baseUrl).intercept({
Apparently an oversight. Will be fixed.

2023-11-14 18:10 UTC, oliversalzburg commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +import { EndpointMethod } from "../endpoint-mocker.types";
Will be fixed.

2023-11-14 18:10 UTC, oliversalzburg commented on src/endpoint-mocker/abstract-endpoint-mocker.ts
> +  }
It could probably be moved to the test suites themselves. Of course, all consumers of this package will have to do that too for all their test suites, if they use Jest. Could be painful. Or maybe I'm missing a better solution.

2023-11-14 18:10 UTC, oliversalzburg commented on scripts/endpoint-requests.js
> -    ] = `new MoctokitRequestMocker<"${path}", "${method}">(baseUrl, endpoints["${scope}"]["${endpoint.id}"], allowUnmocked).request`;
This behavior is controlled globally through <https://undici.nodejs.org/#/docs/api/MockAgent?id=mockagentdisablenetconnect> in undici.

2023-11-21 15:35 UTC, shubhbapna commented on test/moctokit/request-response-mocker.test.ts
> -import axios from "axios";
hmm this PR would break backward compatibility altogether in the case. I think a better solution would be to have nock and as well as undici mocks. What do you think?

2023-11-21 15:38 UTC, shubhbapna commented on scripts/endpoint-requests.js
> -    ] = `new MoctokitRequestMocker<"${path}", "${method}">(baseUrl, endpoints["${scope}"]["${endpoint.id}"], allowUnmocked).request`;
Could we keep such that the user can decide the behaviour? So if the user passes `allowUnmocked` as `false` then we call `MockAgent.disableNetConnect()` otherwise we do nothing

2023-11-21 15:40 UTC, shubhbapna commented on src/endpoint-mocker/abstract-endpoint-mocker.ts
> +  }
I see, lets keep it for now

2023-11-21 15:40 UTC, shubhbapna commented on src/endpoint-mocker/response/abstract-response-mocker.ts
> +            "content-type": this.getContentTypeForResponseData(response.data),
Okay, but allow the user to override it. Probably shift line 71 above 70

2023-11-22 15:07 UTC, oliversalzburg reviewed
I hope I addressed everything :)

2023-11-22 15:07 UTC, oliversalzburg commented on scripts/endpoint-requests.js
> -    ] = `new MoctokitRequestMocker<"${path}", "${method}">(baseUrl, endpoints["${scope}"]["${endpoint.id}"], allowUnmocked).request`;
I'm doing that in `EndpointMocker` actually 😊

2023-11-22 15:13 UTC, oliversalzburg commented on test/moctokit/request-response-mocker.test.ts
> -import axios from "axios";
That would definitely be an option.

I've seen several other projects introduce a similar breaking change when they moved to Node18 and beyond. Many projects only support Node18 and newer now, at least in my part of the bubble :)

However, as I remember, the new Octokit tooling also has a new fetch-based, and the old interface still built in.

This also made me think about if both paths should be implemented in mock-github. I felt like users of old octokit versions could still use the existing version of mock-github; the path into the future will be entirely fetch-based, as that is what the latest implementations from GitHub use. If you are mocking Octokit, it is likely that you want to work with the latest supported version, which uses fetch by default in the latest version, and is highly likely to continue doing so moving ahead.

Given all that, I felt like it could make sense to just accept the breaking change and focus on a single implementation.

If you think it's worth the effort to maintain the two paths, I'm happy to work on that as well :)

2023-12-27 07:26 UTC, shubhbapna commented
Hi, sorry I was away for sometime. I was recently made aware of the ongoing effort in nock to support undici: https://github.com/nock/nock/pull/2517

They estimate that this work will be done by January. I would rather wait for this and have the mocking entirely handled by `nock` which in the longer run will be better and will also reduce the maintenance load on this project. So for now I will mark this pull request as draft. Sorry for the inconvenience and thank you so much for the contribution!

2023-12-28 09:25 UTC, closed without merging