feat!: Use nock@14, support node@20/fetch
kiegroup/mock-github pull request #83
Opened 2024-05-31 09:18 UTC by oliversalzburg

The `toStrictEqual` calls had to be replaced, because it falsely assumed to receive back the exact same in-memory object, which seems like an unrealistic expectation in the test, that was only satisfied through the previous dependency implementation details.

Fixes #77

2024-06-07 16:19 UTC, shubhbapna commented
Thank you for your PR! I am currently on vacation and will be back on 12th June

2024-06-19 16:16 UTC, shubhbapna requested changes

2024-06-19 16:16 UTC, shubhbapna commented on .github/workflows/publish.yml
> +          node-version: 22
The current LTS is node 20 so I would change it to that (and in all the other workflows as well)

2024-06-19 16:16 UTC, shubhbapna commented on .github/workflows/pull_request.yml
> +        node-version: [20,22]
Could you add node 18 to the list as well

2024-06-19 16:16 UTC, shubhbapna commented on package.json
> +    "node": "20"
Could you change this to node 18

2024-06-22 12:45 UTC, oliversalzburg commented on package.json
> +    "node": "20"
I realized that this is too strict anyway, and fixed this as `>=18`.

2024-06-28 17:44 UTC, shubhbapna requested changes

2024-06-28 17:44 UTC, shubhbapna commented on .github/workflows/publish.yml
> +          node-version: 20
Should be node 18 since that is the minimum supported version

2024-06-28 17:44 UTC, shubhbapna commented on .github/workflows/pull_request.yml
> +          node-version: 22
Should be node 18

2024-06-28 17:44 UTC, shubhbapna commented on .github/workflows/report.yml
> +          node-version: 22
Should be node 18

2024-06-28 17:44 UTC, shubhbapna commented on .github/workflows/update.yml
> +          node-version: 22
Should be node 18

2024-07-17 17:56 UTC, shubhbapna approved these changes

2024-07-17 17:57 UTC, merged

2024-07-17 18:28 UTC, oliversalzburg commented
> So sorry for the delay, working on this and should have a beta release available by EOD

I really appreciate that you took the time to evaluate this. I only hope that we can make this amazing project work with the latest libraries.